const legacyLessons=[
 {id:'greetings',level:'HSK 1',num:'01',title:'Chào hỏi & giới thiệu',zh:'问候与介绍',desc:'Chào đồng nghiệp, giới thiệu tên, nghề nghiệp và công ty.',time:12,color:'red',words:[['你好','nǐ hǎo','xin chào'],['叫','jiào','tên là / gọi'],['名字','míngzi','tên'],['认识','rènshi','quen, biết'],['公司','gōngsī','công ty'],['工作','gōngzuò','làm việc'],['同事','tóngshì','đồng nghiệp'],['高兴','gāoxìng','vui']],patterns:[['我是 + danh từ','我是工程师。','Tôi là kỹ sư.'],['我叫 + tên','我叫小明。','Tôi tên là Tiểu Minh.'],['我在 + nơi + 工作','我在一家科技公司工作。','Tôi làm tại một công ty công nghệ.']],tip:'是 nối chủ ngữ với danh từ. Khi nói nơi làm việc, dùng 在 trước địa điểm.',warning:['Không nói “我是工作工程师”.','认识你很高兴 vẫn hiểu được, nhưng 很高兴认识你 tự nhiên hơn.']},
 {id:'time',level:'HSK 1',num:'02',title:'Thời gian & lịch làm việc',zh:'时间与日程',desc:'Nói giờ, ngày, lịch hẹn và thời điểm bắt đầu công việc.',time:13,words:[['今天','jīntiān','hôm nay'],['明天','míngtiān','ngày mai'],['现在','xiànzài','bây giờ'],['上午','shàngwǔ','buổi sáng'],['下午','xiàwǔ','buổi chiều'],['点','diǎn','giờ'],['开会','kāihuì','họp'],['时间','shíjiān','thời gian']],patterns:[['现在 + thời gian','现在九点。','Bây giờ là 9 giờ.'],['…点 + động từ','我们十点开会。','Chúng ta họp lúc 10 giờ.'],['什么时候…？','你什么时候有时间？','Khi nào bạn có thời gian?']],tip:'Tiếng Trung nói thời gian từ lớn đến nhỏ: ngày → buổi → giờ → phút.',warning:['九点上午 ❌ → 上午九点 ✓','Hỏi thời gian dùng 什么时候, hỏi mấy giờ dùng 几点.']},
 {id:'requests',level:'HSK 1',num:'03',title:'Nhờ giúp & yêu cầu lịch sự',zh:'请求与帮助',desc:'Nhờ đồng nghiệp hỗ trợ và phản hồi lịch sự.',time:14,words:[['请','qǐng','xin, mời'],['帮','bāng','giúp'],['可以','kěyǐ','có thể, được phép'],['一下','yíxià','một chút'],['问题','wèntí','vấn đề'],['需要','xūyào','cần'],['谢谢','xièxie','cảm ơn'],['不客气','bú kèqi','không có gì']],patterns:[['请 + động từ','请看一下这个文件。','Vui lòng xem tài liệu này.'],['可以…吗？','可以帮我一下吗？','Bạn có thể giúp tôi một chút không?'],['我需要 + danh từ','我需要你的帮助。','Tôi cần sự giúp đỡ của bạn.']],tip:'Thêm 请, 一下 hoặc 可以…吗 làm yêu cầu mềm và lịch sự hơn.',warning:['帮我! nghe như mệnh lệnh; dùng 请帮我一下。','可以 mang nghĩa có thể hoặc được phép, tùy ngữ cảnh.']},
 {id:'progress',level:'HSK 2',num:'04',title:'Báo cáo tiến độ',zh:'汇报进度',desc:'Nói việc đã làm, đang làm và thời hạn hoàn thành.',time:16,words:[['已经','yǐjīng','đã'],['正在','zhèngzài','đang'],['完成','wánchéng','hoàn thành'],['项目','xiàngmù','dự án'],['报告','bàogào','báo cáo'],['还','hái','vẫn, còn'],['准备','zhǔnbèi','chuẩn bị'],['以前','yǐqián','trước đây']],patterns:[['已经…了','我已经完成报告了。','Tôi đã hoàn thành báo cáo rồi.'],['正在 + V','我们正在准备会议。','Chúng tôi đang chuẩn bị cuộc họp.'],['还没(有) + V','项目还没完成。','Dự án vẫn chưa hoàn thành.']],tip:'已经…了 nhấn mạnh đã hoàn tất; 正在 nhấn mạnh đang diễn ra; 还没 là vẫn chưa.',warning:['Không dùng 了 sau 还没: 我还没完成。','正在 thường đứng ngay trước động từ.']},
 {id:'meetings',level:'HSK 2',num:'05',title:'Trao đổi trong cuộc họp',zh:'会议沟通',desc:'Nêu ý kiến, đồng ý, chưa hiểu và xin giải thích.',time:17,words:[['觉得','juéde','cảm thấy, cho rằng'],['同意','tóngyì','đồng ý'],['意见','yìjiàn','ý kiến'],['明白','míngbai','hiểu'],['解释','jiěshì','giải thích'],['重要','zhòngyào','quan trọng'],['办法','bànfǎ','cách, biện pháp'],['讨论','tǎolùn','thảo luận']],patterns:[['我觉得…','我觉得这个办法很好。','Tôi thấy cách này rất tốt.'],['我同意…','我同意你的意见。','Tôi đồng ý với ý kiến của bạn.'],['能再说一遍吗？','这部分我没明白，能再说一遍吗？','Phần này tôi chưa hiểu, có thể nói lại không?']],tip:'Mở đầu bằng 我觉得 giúp ý kiến bớt trực diện và tự nhiên trong cuộc họp.',warning:['意见 là ý kiến, không phải “ý kiến phản đối”.','没明白 tự nhiên hơn 不明白 khi nói chưa hiểu điều vừa nghe.']},
 {id:'email',level:'HSK 2',num:'06',title:'Tin nhắn & email công việc',zh:'工作消息与邮件',desc:'Gửi tài liệu, xác nhận đã nhận và phản hồi đúng lúc.',time:15,words:[['邮件','yóujiàn','email'],['文件','wénjiàn','tài liệu, tệp'],['发送','fāsòng','gửi'],['收到','shōudào','nhận được'],['回复','huífù','phản hồi'],['确认','quèrèn','xác nhận'],['附件','fùjiàn','tệp đính kèm'],['马上','mǎshàng','ngay lập tức']],patterns:[['把 + O + V','请把文件发给我。','Vui lòng gửi tài liệu cho tôi.'],['收到…了','我收到你的邮件了。','Tôi đã nhận email của bạn.'],['V + 好 + 以后','确认好以后，请回复我。','Sau khi xác nhận xong, vui lòng phản hồi tôi.']],tip:'把 đưa đối tượng lên trước động từ, thường dùng khi đối tượng bị xử lý hoặc thay đổi.',warning:['把 câu cần một động từ có tác động rõ lên đồ vật.','发给我 = gửi cho tôi; 给我发 cũng đúng trong giao tiếp.']},
 {id:'deadlines',level:'HSK 3',num:'07',title:'Kế hoạch & thời hạn',zh:'计划与期限',desc:'Sắp xếp nhiệm vụ, cam kết deadline và nói điều kiện.',time:18,words:[['计划','jìhuà','kế hoạch'],['任务','rènwu','nhiệm vụ'],['按时','ànshí','đúng giờ, đúng hạn'],['提前','tíqián','sớm hơn'],['推迟','tuīchí','hoãn lại'],['如果','rúguǒ','nếu'],['必须','bìxū','phải'],['安排','ānpái','sắp xếp']],patterns:[['如果…就…','如果没问题，我们就按时完成。','Nếu không có vấn đề, chúng ta sẽ hoàn thành đúng hạn.'],['必须 + V','这个任务必须今天完成。','Nhiệm vụ này phải hoàn thành hôm nay.'],['打算 + V','我打算提前准备。','Tôi dự định chuẩn bị sớm.']],tip:'如果…就… thể hiện điều kiện và kết quả. Trong giao tiếp, 就 có thể lược nhưng giữ lại sẽ rõ hơn.',warning:['必须 là bắt buộc; 应该 là nên, mức độ nhẹ hơn.','计划 có thể là danh từ hoặc động từ.']},
 {id:'problems',level:'HSK 3',num:'08',title:'Nêu vấn đề & đề xuất giải pháp',zh:'问题与解决方案',desc:'Mô tả sự cố, nguyên nhân và đề xuất cách xử lý.',time:18,words:[['发现','fāxiàn','phát hiện'],['原因','yuányīn','nguyên nhân'],['解决','jiějué','giải quyết'],['影响','yǐngxiǎng','ảnh hưởng'],['及时','jíshí','kịp thời'],['检查','jiǎnchá','kiểm tra'],['应该','yīnggāi','nên'],['建议','jiànyì','đề xuất']],patterns:[['因为…所以…','因为系统有问题，所以工作被推迟了。','Vì hệ thống có vấn đề nên công việc bị hoãn.'],['应该 + V','我们应该先检查原因。','Chúng ta nên kiểm tra nguyên nhân trước.'],['建议 + người + V','我建议大家再讨论一下。','Tôi đề nghị mọi người thảo luận thêm.']],tip:'因为…所以… giúp diễn đạt quan hệ nguyên nhân–kết quả rõ ràng; có thể dùng cả hai vế.',warning:['原因 là nguyên nhân; 因为 là liên từ “bởi vì”.','建议 vừa là danh từ “đề xuất”, vừa là động từ “đề nghị”.']},
 {id:'clients',level:'HSK 3',num:'09',title:'Giao tiếp với khách hàng',zh:'客户沟通',desc:'Xác nhận nhu cầu, xin lỗi và hẹn phản hồi chuyên nghiệp.',time:19,words:[['客户','kèhù','khách hàng'],['要求','yāoqiú','yêu cầu'],['满意','mǎnyì','hài lòng'],['负责','fùzé','phụ trách'],['联系','liánxì','liên hệ'],['抱歉','bàoqiàn','xin lỗi'],['尽快','jǐnkuài','sớm nhất có thể'],['情况','qíngkuàng','tình hình']],patterns:[['对…负责','我负责这个客户。','Tôi phụ trách khách hàng này.'],['会尽快…','我们会尽快回复您。','Chúng tôi sẽ phản hồi quý khách sớm nhất.'],['先…再…','我先了解情况，再联系您。','Tôi sẽ tìm hiểu tình hình trước rồi liên hệ lại.']],tip:'Dùng 您 thay 你 khi nói với khách hàng để thể hiện sự tôn trọng.',warning:['抱歉 trang trọng hơn 对不起 trong công việc.','尽快 không phải một giờ cụ thể; nếu có thể hãy cho khách deadline rõ.']}
];

const legacyConversations=[
 {id:'first-day',label:'Ngày đầu đi làm',icon:'新',title:'Làm quen đồng nghiệp',desc:'Chào hỏi và giới thiệu bản thân trong ngày đầu.',lines:[['A','你好！你是新同事吗？','Nǐ hǎo! Nǐ shì xīn tóngshì ma?','Xin chào! Bạn là đồng nghiệp mới phải không?'],['B','是的，我叫小明。很高兴认识你！','Shì de, wǒ jiào Xiǎomíng. Hěn gāoxìng rènshi nǐ!','Đúng vậy, tôi tên Tiểu Minh. Rất vui được gặp bạn!'],['A','我也很高兴认识你。你在哪个部门工作？','Wǒ yě hěn gāoxìng rènshi nǐ. Nǐ zài nǎge bùmén gōngzuò?','Tôi cũng rất vui được gặp bạn. Bạn làm ở bộ phận nào?'],['B','我在技术部工作。','Wǒ zài jìshù bù gōngzuò.','Tôi làm ở bộ phận kỹ thuật.']]},
 {id:'meeting',label:'Trong cuộc họp',icon:'会',title:'Xin làm rõ ý kiến',desc:'Nói chưa hiểu và đề nghị đồng nghiệp giải thích lại.',lines:[['A','大家对这个计划有什么意见？','Dàjiā duì zhège jìhuà yǒu shénme yìjiàn?','Mọi người có ý kiến gì về kế hoạch này?'],['B','我觉得时间有点儿短。','Wǒ juéde shíjiān yǒudiǎnr duǎn.','Tôi thấy thời gian hơi ngắn.'],['A','你的意思是我们应该推迟吗？','Nǐ de yìsi shì wǒmen yīnggāi tuīchí ma?','Ý bạn là chúng ta nên hoãn lại phải không?'],['B','不是，我建议增加两个人。','Bú shì, wǒ jiànyì zēngjiā liǎng ge rén.','Không, tôi đề nghị tăng thêm hai người.']]},
 {id:'deadline',label:'Báo cáo tiến độ',icon:'进',title:'Cập nhật với quản lý',desc:'Báo việc đã xong, việc còn lại và cam kết thời hạn.',lines:[['A','项目现在怎么样了？','Xiàngmù xiànzài zěnmeyàng le?','Dự án hiện giờ thế nào rồi?'],['B','报告已经完成了，数据还在检查。','Bàogào yǐjīng wánchéng le, shùjù hái zài jiǎnchá.','Báo cáo đã xong, dữ liệu vẫn đang được kiểm tra.'],['A','明天下午能完成吗？','Míngtiān xiàwǔ néng wánchéng ma?','Chiều mai có thể hoàn thành không?'],['B','没问题，我会按时完成。','Méi wèntí, wǒ huì ànshí wánchéng.','Không vấn đề, tôi sẽ hoàn thành đúng hạn.']]},
 {id:'client',label:'Với khách hàng',icon:'客',title:'Xin lỗi và hẹn phản hồi',desc:'Tiếp nhận vấn đề một cách bình tĩnh và chuyên nghiệp.',lines:[['A','我们还没收到文件。','Wǒmen hái méi shōudào wénjiàn.','Chúng tôi vẫn chưa nhận được tài liệu.'],['B','非常抱歉，我马上检查一下。','Fēicháng bàoqiàn, wǒ mǎshàng jiǎnchá yíxià.','Thành thật xin lỗi, tôi sẽ kiểm tra ngay.'],['A','今天可以发给我们吗？','Jīntiān kěyǐ fā gěi wǒmen ma?','Hôm nay có thể gửi cho chúng tôi không?'],['B','可以，我会在下午三点以前发给您。','Kěyǐ, wǒ huì zài xiàwǔ sān diǎn yǐqián fā gěi nín.','Được, tôi sẽ gửi quý khách trước 3 giờ chiều.']]}
];

const legacyQuiz=[
 {type:'TỪ VỰNG',q:'“同事” có nghĩa là gì?',o:['Khách hàng','Đồng nghiệp','Quản lý'],a:1,e:'同事 (tóngshì) nghĩa là đồng nghiệp, người làm cùng tổ chức.'},
 {type:'CẤU TRÚC',q:'Chọn câu đúng để nói “Tôi làm việc tại công ty này”.',o:['我是这个公司工作。','我在这个公司工作。','我工作是这个公司。'],a:1,e:'Nói nơi diễn ra hành động: chủ ngữ + 在 + địa điểm + động từ.'},
 {type:'GIAO TIẾP',q:'Muốn nhờ đồng nghiệp xem tài liệu một cách lịch sự, bạn nói:',o:['你看文件！','请看一下这个文件。','文件看你。'],a:1,e:'请 + động từ và 一下 làm yêu cầu mềm, lịch sự hơn.'},
 {type:'THỜI GIAN',q:'Cách nói đúng của “9 giờ sáng” là:',o:['九点上午','上午九点','九上午点'],a:1,e:'Thứ tự thời gian đi từ lớn đến nhỏ: buổi → giờ.'},
 {type:'NGỮ PHÁP',q:'我 ___ 完成报告了。 (Tôi đã hoàn thành báo cáo rồi.)',o:['正在','已经','还没'],a:1,e:'已经…了 biểu thị hành động đã hoàn tất.'},
 {type:'NGỮ PHÁP',q:'我们 ___ 准备会议。 (Chúng tôi đang chuẩn bị cuộc họp.)',o:['正在','已经','以前'],a:0,e:'正在 đứng trước động từ để nhấn mạnh hành động đang diễn ra.'},
 {type:'CUỘC HỌP',q:'Câu nào phù hợp để nêu ý kiến mềm mại?',o:['你错了。','我觉得这个办法更好。','必须听我的。'],a:1,e:'我觉得… (tôi thấy/cho rằng…) giúp nêu quan điểm lịch sự hơn.'},
 {type:'EMAIL',q:'请把文件 ___ 我。',o:['发给','收到','完成'],a:0,e:'发给我 nghĩa là gửi cho tôi. Mẫu 把 + tân ngữ + động từ nhấn mạnh việc xử lý tân ngữ.'},
 {type:'ĐIỀU KIỆN',q:'如果没有问题，我们 ___ 按时完成。',o:['才','就','还'],a:1,e:'Cặp 如果…就… diễn đạt “nếu… thì…”.'},
 {type:'GIẢI QUYẾT VẤN ĐỀ',q:'“因为系统有问题，___ 工作被推迟了。”',o:['但是','所以','如果'],a:1,e:'因为…所以… nối nguyên nhân với kết quả: bởi vì… nên…'},
 {type:'KHÁCH HÀNG',q:'Cách xưng hô lịch sự với khách hàng là:',o:['你','您','他'],a:1,e:'您 (nín) là dạng kính trọng của 你, phù hợp khi nói với khách hàng.'},
 {type:'MẸO DÙNG TỪ',q:'Câu nào thể hiện “nên”, không phải “bắt buộc”?',o:['我们应该检查。','我们必须检查。','我们正在检查。'],a:0,e:'应该 = nên; 必须 = phải/bắt buộc; 正在 = đang.'}
];

const allWords=lessons.flatMap(l=>l.words.map(w=>({hanzi:w[0],pinyin:w[1],meaning:w[2],category:l.title,level:l.level,example:wordExample(w[0])})));
function wordExample(word){const map={'你好':'你好，很高兴认识你。','叫':'我叫小明。','越南':'我是越南人。','汉语':'我会说一点儿汉语。','家':'我家有四口人。','朋友':'她是我的好朋友。','今天':'今天是五月十号。','明天':'明天见！','点':'我八点起床。','起床':'我每天七点起床。','正在':'我正在看书。','已经':'我已经吃饭了。','米饭':'我喜欢吃米饭。','茶':'我想喝茶。','多少':'这个多少钱？','衣服':'这件衣服很好看。','便宜':'这个很便宜。','地铁':'我们坐地铁去。','旁边':'银行在学校旁边。','喜欢':'我喜欢听音乐。','下雨':'今天下雨了。','身体':'你的身体怎么样？','头疼':'我今天有点儿头疼。','应该':'你应该多休息。','打算':'我打算明天去医院。'};return map[word]||`请记住“${word}”这个词。`}

const saved=JSON.parse(localStorage.getItem('hanziHskProgress')||'{}');
const progress={completed:(saved.completed||[]).filter(id=>lessons.some(l=>l.id===id)),best:saved.best||0,attempts:saved.attempts||0,correct:saved.correct||0,minutes:saved.minutes||0,streak:saved.streak||3,history:saved.history||[]};
const state={lesson:'greetings',category:'Tất cả',scenario:'first-day',question:0,score:0,answered:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

function save(){localStorage.setItem('hanziHskProgress',JSON.stringify(progress));updateUI()}
function go(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(view==='roadmap')renderRoadmap();if(view==='vocabulary')renderWords();if(view==='conversation')renderConversation();if(view==='progress')renderProgress()}
$$('[data-view]').forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.view)});$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');

function renderRoadmap(level='all'){$('#lessonGrid').innerHTML=lessons.filter(l=>level==='all'||l.level===level).map(l=>`<button class="lesson-card" data-lesson="${l.id}"><span class="lesson-number">${l.num}</span><span class="lesson-level">${progress.completed.includes(l.id)?'✓ ĐÃ HỌC':l.level}</span><h3>${l.title}<small>${l.zh}</small></h3><p>${l.desc}</p><footer><span>◷ ${l.time} phút · ${l.words.length} từ</span><b>Học ngay →</b></footer></button>`).join('');bindLessons();const pct=Math.round(progress.completed.length/lessons.length*100);$('#roadmapPercent').textContent=pct+'%';$('#roadmapDone').textContent=progress.completed.length;$('#roadmapBar').style.width=pct+'%'}
function bindLessons(){$$('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson))}
function openLesson(id){state.lesson=id;renderLesson();go('lesson')}
function renderLesson(){const l=lessons.find(x=>x.id===state.lesson);$('#lessonContent').innerHTML=`<header class="lesson-header"><div><span class="level-pill">${l.level} · BÀI ${l.num}</span><h1>${l.title} · ${l.zh}</h1><p>${l.desc} Nội dung bám sát cấp độ HSK và tình huống đời sống thường ngày.</p></div><div class="lesson-time"><b>${l.time}</b><span>PHÚT HỌC</span></div></header><div class="lesson-layout"><article class="lesson-main"><section class="lesson-block"><div class="block-title"><span>01</span><div><small>TỪ CỐT LÕI</small><h2>Nhìn – nghe – dùng</h2></div></div><div class="vocab-list">${l.words.map(w=>`<div class="vocab-row"><b>${w[0]}</b><div><strong>${w[1]}</strong><small>${w[2]}</small></div><button class="speak" data-speak="${w[0]}" aria-label="Nghe ${w[0]}">♪</button></div>`).join('')}</div></section><section class="lesson-block"><div class="block-title"><span>02</span><div><small>CẤU TRÚC</small><h2>Mẫu câu dùng ngay</h2></div></div><div class="pattern-list">${l.patterns.map(p=>`<div class="pattern"><code>${p[0]}</code><p>${p[1]}</p><small>${p[2]}</small> <button class="speak" data-speak="${p[1]}" aria-label="Nghe câu">♪</button></div>`).join('')}</div></section><section class="lesson-block"><div class="block-title"><span>03</span><div><small>MẸO NHỚ</small><h2>Hiểu bản chất</h2></div></div><div class="note-box">${l.tip}</div></section></article><aside class="lesson-side"><div class="warning"><p class="eyebrow">LƯU Ý DỄ SAI</p><h3>Tránh nói máy móc</h3><ul>${l.warning.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><p class="eyebrow">THỰC HÀNH 1 PHÚT</p><h3>Tự tạo câu</h3><ul><li>Đọc to mỗi câu mẫu 3 lần.</li><li>Thay tên, thời gian hoặc đồ vật bằng thông tin thật.</li><li>Không nhìn mẫu và nói lại.</li></ul></div><button class="primary complete-button" id="completeLesson">${progress.completed.includes(l.id)?'Ôn lại bằng bài tập':'Hoàn thành bài học'} →</button></aside></div>`;$$('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$('#completeLesson').onclick=()=>completeLesson(l)}
function completeLesson(l){if(!progress.completed.includes(l.id)){progress.completed.push(l.id);progress.minutes+=l.time;progress.history.unshift({title:l.title,detail:`Hoàn thành bài ${l.num} · ${l.time} phút`});save();toast('Đã hoàn thành bài học!')}go('practice')}

function renderWordTabs(){const cats=['Tất cả',...new Set(lessons.map(l=>l.title))];$('#wordTabs').innerHTML=cats.map(c=>`<button class="${c===state.category?'active':''}" data-category="${c}">${c}</button>`).join('');$$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderWords()})}
function renderWords(){renderWordTabs();const q=$('#wordSearch').value.trim().toLowerCase();const words=allWords.filter(w=>(state.category==='Tất cả'||w.category===state.category)&&(!q||`${w.hanzi} ${w.pinyin} ${w.meaning}`.toLowerCase().includes(q)));$('#wordGrid').innerHTML=words.map(w=>`<article class="word-card"><span class="hanzi">${w.hanzi}</span><span class="pinyin">${w.pinyin}</span><div class="meaning">${w.meaning}</div><p class="example">${w.example}</p><button class="speak" data-speak="${w.hanzi}">♪ Nghe</button></article>`).join('')||'<p class="empty">Không tìm thấy từ phù hợp.</p>';$$('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.speak))}
$('#wordSearch').oninput=renderWords;

function renderScenarioTabs(){$('#scenarioTabs').innerHTML=conversations.map(s=>`<button class="${s.id===state.scenario?'active':''}" data-scenario="${s.id}">${s.label}</button>`).join('');$$('[data-scenario]').forEach(b=>b.onclick=()=>{state.scenario=b.dataset.scenario;renderConversation()})}
function renderConversation(){renderScenarioTabs();const s=conversations.find(x=>x.id===state.scenario);$('#conversationContent').innerHTML=`<article class="conversation-card"><div class="scene-info"><span>${s.icon}</span><h2>${s.title}</h2><p>${s.desc}</p><button class="primary gold" id="playDialogue">♪ Nghe toàn bộ</button></div><div class="dialogue-list">${s.lines.map(l=>`<div class="dialogue-line"><span>${l[0]}</span><div><b>${l[1]}</b><i>${l[2]}</i><small>${l[3]}</small></div><button class="speak" data-speak="${l[1]}">♪</button></div>`).join('')}</div></article>`;$$('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$('#playDialogue').onclick=()=>speak(s.lines.map(l=>l[1]).join('。'))}

function startQuiz(){state.question=0;state.score=0;state.answered=false;$('#quizIntro').classList.add('hidden');$('#resultArea').classList.add('hidden');$('#quizArea').classList.remove('hidden');renderQuestion()}
function renderQuestion(){const q=quiz[state.question];state.answered=false;$('#quizArea').innerHTML=`<div class="quiz-progress"><div><i style="width:${state.question/quiz.length*100}%"></i></div><span>${state.question+1} / ${quiz.length}</span></div><p class="question-type">${q.type}</p><h2 class="quiz-question">${q.q}</h2><div class="answers">${q.o.map((x,i)=>`<button class="answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b><span>${x}</span></button>`).join('')}</div><div id="feedback"></div>`;$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
function answer(choice){if(state.answered)return;state.answered=true;const q=quiz[state.question],correct=choice===q.a;if(correct)state.score++;$$('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.a)b.classList.add('correct');if(i===choice&&!correct)b.classList.add('wrong')});$('#feedback').innerHTML=`<div class="feedback ${correct?'ok':'no'}"><b>${correct?'Chính xác!':'Chưa đúng — đáp án '+String.fromCharCode(65+q.a)}</b><br>${q.e}</div><button class="primary next-button" id="nextQuestion">${state.question===quiz.length-1?'Xem kết quả':'Câu tiếp theo →'}</button>`;$('#nextQuestion').onclick=()=>{state.question++;state.question<quiz.length?renderQuestion():showResult()}}
function showResult(){const pct=Math.round(state.score/quiz.length*100);progress.attempts+=quiz.length;progress.correct+=state.score;progress.best=Math.max(progress.best,pct);progress.minutes+=8;progress.history.unshift({title:'Luyện tập tổng hợp',detail:`${state.score}/${quiz.length} câu đúng · 8 phút`});save();$('#quizArea').classList.add('hidden');$('#resultArea').classList.remove('hidden');$('#resultArea').innerHTML=`<div class="result"><div class="score-circle" style="--score:${pct*3.6}deg"><b>${pct}</b></div><p class="eyebrow">KẾT QUẢ CỦA BẠN</p><h2>${pct>=80?'做得很好！Rất tốt!':pct>=60?'进步了！Đang tiến bộ!':'再试一次！Thử lại nhé!'}</h2><p>Bạn trả lời đúng ${state.score}/${quiz.length} câu. ${pct>=80?'Hãy chuyển sang bài giao tiếp và nói thành tiếng.':'Xem lại giải thích và làm lại để nhớ chắc hơn.'}</p><div class="result-actions"><button class="secondary" id="retry">Làm lại</button><button class="primary" id="reviewRoadmap">Xem lộ trình →</button></div></div>`;$('#retry').onclick=startQuiz;$('#reviewRoadmap').onclick=()=>go('roadmap')}
$('#startQuiz').onclick=startQuiz;

function renderProgress(){$('#masteryList').innerHTML=lessons.map(l=>{const done=progress.completed.includes(l.id);return `<div class="mastery-row"><span>${l.num}</span><div><strong>${l.title}</strong><div><i style="width:${done?100:0}%"></i></div></div><b>${done?'100%':'0%'}</b></div>`}).join('');$('#historyList').innerHTML=progress.history.length?progress.history.slice(0,7).map(h=>`<div class="history-item"><strong>${h.title}</strong><small>${h.detail}</small></div>`).join(''):'<p class="empty">Hoàn thành một bài để bắt đầu ghi lại hành trình.</p>'}
function updateUI(){const accuracy=progress.attempts?Math.round(progress.correct/progress.attempts*100):null;$$('[data-streak]').forEach(x=>x.textContent=progress.streak);$('#homeLessons').textContent=`${progress.completed.length} / ${lessons.length}`;$('#homeWords').textContent=progress.completed.reduce((n,id)=>n+(lessons.find(l=>l.id===id)?.words.length||0),0);$('#homeAccuracy').textContent=accuracy!==null?accuracy+'%':'—';$('#progressLessons').textContent=`${progress.completed.length} / ${lessons.length}`;$('#progressBest').textContent=progress.best?progress.best+'/100':'—';$('#progressMinutes').textContent=progress.minutes+' phút'}
function speak(text){if(!('speechSynthesis'in window))return toast('Trình duyệt chưa hỗ trợ phát âm.');const synth=window.speechSynthesis;const active=document.activeElement?.classList.contains('speak')?document.activeElement:null;$$('.speak').forEach(b=>{b.classList.remove('is-speaking');b.disabled=false});if(active){active.classList.add('is-speaking');active.disabled=true}const play=()=>{const utterance=new SpeechSynthesisUtterance(text);const voices=synth.getVoices();utterance.voice=voices.find(v=>/^zh(-|_)CN/i.test(v.lang))||voices.find(v=>v.lang.toLowerCase().startsWith('zh'))||null;utterance.lang='zh-CN';utterance.rate=.72;utterance.pitch=1;utterance.volume=1;const reset=()=>{if(active){active.classList.remove('is-speaking');active.disabled=false}};utterance.onend=reset;utterance.onerror=()=>{reset();toast('Không phát được âm thanh. Hãy kiểm tra âm lượng trình duyệt.')};synth.speak(utterance)};synth.cancel();setTimeout(play,80)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}

$$('[data-level]').forEach(b=>b.onclick=()=>{$$('[data-level]').forEach(x=>x.classList.toggle('active',x===b));renderRoadmap(b.dataset.level)});
document.addEventListener('click',e=>{if(innerWidth<=850&&!$('#sidebar').contains(e.target)&&!$('#menuButton').contains(e.target))$('#sidebar').classList.remove('open')});
renderRoadmap();renderWords();renderConversation();renderLesson();updateUI();bindLessons();

const chatPanel=$('#chatPanel'),chatMessages=$('#chatMessages'),chatInput=$('#chatInput');
function openChat(){chatPanel.classList.add('open');chatPanel.setAttribute('aria-hidden','false');setTimeout(()=>chatInput.focus(),220)}
function closeChat(){chatPanel.classList.remove('open');chatPanel.setAttribute('aria-hidden','true');$('#chatToggle').focus()}
$('#chatToggle').onclick=openChat;$('#chatClose').onclick=closeChat;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&chatPanel.classList.contains('open'))closeChat()});
function chatAnswer(text){const q=text.toLowerCase();
 if(q.includes('giới thiệu')||q.includes('tên')||q.includes('自我介绍'))return '<b>Giới thiệu ngắn:</b><br>你好，我叫小明。<br><i>Nǐ hǎo, wǒ jiào Xiǎomíng.</i><br>Xin chào, tôi tên Tiểu Minh.<br><br>我是越南人。我会说一点儿汉语。<br><i>Wǒ shì Yuènán rén. Wǒ huì shuō yìdiǎnr Hànyǔ.</i><br>Tôi là người Việt Nam. Tôi biết nói một chút tiếng Trung.';
 if(q.includes('已经')||q.includes('正在')||q.includes('đã')||q.includes('đang'))return '<b>已经 yǐjīng</b> = đã: 我已经完成了。 (Tôi đã hoàn thành.)<br><br><b>正在 zhèngzài</b> = đang: 我正在准备会议。 (Tôi đang chuẩn bị cuộc họp.)<br><br>Mẹo: 已经 thường đi với 了; 正在 đứng ngay trước động từ.';
 if(q.includes('giúp')||q.includes('nhờ')||q.includes('帮'))return 'Cách nhờ lịch sự:<br><b>可以帮我一下吗？</b><br><i>Kěyǐ bāng wǒ yíxià ma?</i><br>Bạn có thể giúp tôi một chút không?<br><br>Thêm <b>请</b>, <b>一下</b> hoặc mẫu <b>可以…吗？</b> để câu mềm hơn.';
 if(q.includes('ăn')||q.includes('uống')||q.includes('nhà hàng')||q.includes('点菜'))return 'Gọi món đơn giản:<br><b>我要一碗面条。</b><br><i>Wǒ yào yì wǎn miàntiáo.</i><br>Tôi muốn một bát mì.<br><br>Hỏi giá: <b>这个多少钱？</b> — Cái này bao nhiêu tiền?';
 if(q.includes('đường')||q.includes('đi lại')||q.includes('地铁')||q.includes('怎么走'))return 'Hỏi đường:<br><b>请问，地铁站在哪儿？</b><br><i>Qǐngwèn, dìtiě zhàn zài nǎr?</i><br>Xin hỏi, ga tàu điện ở đâu?<br><br><b>离这儿远吗？</b> — Có xa đây không?';
 if(q.includes('sức khỏe')||q.includes('đau')||q.includes('头疼')||q.includes('bệnh'))return 'Hỏi sức khỏe: <b>你怎么了？</b> — Bạn sao vậy?<br><br>我头疼。<i>Wǒ tóuténg.</i> — Tôi đau đầu.<br><br>Lời khuyên: <b>你应该多休息，多喝水。</b> — Bạn nên nghỉ ngơi và uống nhiều nước.';
 if(q.includes('nếu')||q.includes('如果'))return '<b>如果…就…</b> = nếu… thì…<br>如果没问题，我们就按时完成。<br><i>Rúguǒ méi wèntí, wǒmen jiù ànshí wánchéng.</i><br>Nếu không có vấn đề, chúng ta sẽ hoàn thành đúng hạn.';
 if(q.includes('pinyin')||q.includes('phát âm')||q.includes('thanh điệu'))return 'Pinyin có 4 thanh chính: mā (ngang), má (lên), mǎ (xuống–lên), mà (xuống). Hãy nghe nút ♪, đọc chậm từng âm rồi mới ghép cả câu. Thanh 3 đứng trước thanh 3 thường đọc gần giống thanh 2, ví dụ 你好: ní hǎo.';
 const found=allWords.find(w=>q.includes(w.hanzi)||q.includes(w.pinyin.toLowerCase())||q.includes(w.meaning.toLowerCase()));if(found)return `<b>${found.hanzi}</b> · ${found.pinyin}<br>${found.meaning}<br><br>Ví dụ: ${found.example}`;
 return 'Mình chưa nhận ra chủ điểm. Bạn có thể hỏi cụ thể như: <b>cách giới thiệu bản thân</b>, <b>已经 và 正在</b>, <b>gọi món</b>, <b>hỏi đường</b>, <b>sức khỏe</b>, <b>pinyin</b> hoặc nhập một từ Hán trong bài.';
}
function sendChat(text){const value=text.trim();if(!value)return;const safe=value.replace(/[<>]/g,'');chatMessages.insertAdjacentHTML('beforeend',`<div class="chat-message user"><p>${safe}</p></div>`);chatInput.value='';chatMessages.scrollTop=chatMessages.scrollHeight;setTimeout(()=>{chatMessages.insertAdjacentHTML('beforeend',`<div class="chat-message bot"><span>汉</span><p>${chatAnswer(value)}</p></div>`);chatMessages.scrollTop=chatMessages.scrollHeight},300)}
$('#chatForm').onsubmit=e=>{e.preventDefault();sendChat(chatInput.value)};$$('.chat-suggestions button').forEach(b=>b.onclick=()=>sendChat(b.textContent));
