const lessons=[
 {id:'greetings',level:'HSK 1',num:'01',title:'Chào hỏi & giới thiệu',zh:'问候与介绍',desc:'Chào hỏi, giới thiệu tên, quốc tịch và ngôn ngữ.',time:12,words:[['你好','nǐ hǎo','xin chào'],['叫','jiào','tên là'],['名字','míngzi','tên'],['认识','rènshi','quen, biết'],['中国','Zhōngguó','Trung Quốc'],['越南','Yuènán','Việt Nam'],['汉语','Hànyǔ','tiếng Trung'],['高兴','gāoxìng','vui']],patterns:[['我叫 + tên','我叫小明。','Tôi tên là Tiểu Minh.'],['我是 + quốc tịch','我是越南人。','Tôi là người Việt Nam.'],['会 + động từ','我会说一点儿汉语。','Tôi biết nói một chút tiếng Trung.']],tip:'是 dùng trước danh từ; 会 dùng để nói khả năng đã học được.',warning:['Không dùng 是 trước động từ: 我是说汉语 ❌','很高兴认识你 là cách nói tự nhiên: rất vui được gặp bạn.']},
 {id:'family',level:'HSK 1',num:'02',title:'Gia đình & con người',zh:'家人与人物',desc:'Giới thiệu gia đình, tuổi tác và mối quan hệ.',time:13,words:[['家','jiā','nhà, gia đình'],['爸爸','bàba','bố'],['妈妈','māma','mẹ'],['哥哥','gēge','anh trai'],['姐姐','jiějie','chị gái'],['朋友','péngyou','bạn bè'],['岁','suì','tuổi'],['有','yǒu','có']],patterns:[['有 + số lượng','我家有四口人。','Nhà tôi có bốn người.'],['A 是 B','她是我的姐姐。','Cô ấy là chị gái tôi.'],['几岁 / 多大','你今年多大？','Năm nay bạn bao nhiêu tuổi?']],tip:'Lượng từ phổ biến cho người là 个; khi đếm thành viên gia đình thường dùng 口.',warning:['Nói tuổi dùng 岁, không dùng 年.','没 dùng để phủ định 有: 我没有哥哥。']},
 {id:'time',level:'HSK 1',num:'03',title:'Số đếm, ngày giờ',zh:'数字与时间',desc:'Nói số, ngày tháng, giờ và lịch hẹn đơn giản.',time:13,words:[['今天','jīntiān','hôm nay'],['明天','míngtiān','ngày mai'],['星期','xīngqī','tuần, thứ'],['月','yuè','tháng'],['号','hào','ngày'],['点','diǎn','giờ'],['分钟','fēnzhōng','phút'],['时候','shíhou','lúc']],patterns:[['Thời gian + hành động','我八点起床。','Tôi thức dậy lúc 8 giờ.'],['…月…号','今天是五月十号。','Hôm nay là ngày 10 tháng 5.'],['什么时候…？','你什么时候回家？','Khi nào bạn về nhà?']],tip:'Thứ tự thời gian: năm → tháng → ngày → buổi → giờ → phút.',warning:['上午九点 ✓, 九点上午 ❌','两点 dùng 两; số thứ tự và số điện thoại thường dùng 二.']},
 {id:'routine',level:'HSK 2',num:'04',title:'Sinh hoạt hằng ngày',zh:'日常生活',desc:'Mô tả các hoạt động thường ngày và việc đang diễn ra.',time:15,words:[['起床','qǐchuáng','thức dậy'],['吃饭','chīfàn','ăn cơm'],['学习','xuéxí','học'],['睡觉','shuìjiào','ngủ'],['每天','měitiān','mỗi ngày'],['正在','zhèngzài','đang'],['已经','yǐjīng','đã'],['还没','hái méi','vẫn chưa']],patterns:[['正在 + V','我正在看书。','Tôi đang đọc sách.'],['已经…了','我已经吃饭了。','Tôi đã ăn cơm rồi.'],['还没 + V','我还没睡觉。','Tôi vẫn chưa ngủ.']],tip:'正在 = đang diễn ra; 已经…了 = đã xong; 还没 = vẫn chưa.',warning:['Không thêm 了 sau 还没.','每天 thường đi với thói quen, không cần 正在.']},
 {id:'food',level:'HSK 2',num:'05',title:'Ăn uống & gọi món',zh:'饮食与点菜',desc:'Nói sở thích ăn uống, gọi món và hỏi giá.',time:15,words:[['米饭','mǐfàn','cơm'],['面条','miàntiáo','mì sợi'],['水','shuǐ','nước'],['茶','chá','trà'],['好吃','hǎochī','ngon'],['想','xiǎng','muốn'],['要','yào','muốn, cần'],['多少','duōshao','bao nhiêu']],patterns:[['想 + V','我想喝茶。','Tôi muốn uống trà.'],['要 + danh từ','我要一碗面条。','Tôi muốn một bát mì.'],['多少钱？','这个多少钱？','Cái này bao nhiêu tiền?']],tip:'想 thiên về mong muốn; 要 trực tiếp hơn và thường dùng khi gọi món.',warning:['Đồ uống dùng 喝, đồ ăn dùng 吃.','Một bát mì: 一碗面条; nhớ lượng từ 碗.']},
 {id:'shopping',level:'HSK 2',num:'06',title:'Mua sắm & so sánh',zh:'购物与比较',desc:'Hỏi giá, màu sắc, kích cỡ và so sánh đồ vật.',time:16,words:[['买','mǎi','mua'],['卖','mài','bán'],['衣服','yīfu','quần áo'],['颜色','yánsè','màu sắc'],['便宜','piányi','rẻ'],['贵','guì','đắt'],['大','dà','lớn'],['小','xiǎo','nhỏ']],patterns:[['太…了','这件衣服太贵了。','Bộ quần áo này đắt quá.'],['A 比 B + tính từ','红色的比蓝色的贵。','Màu đỏ đắt hơn màu xanh.'],['有点儿 + tính từ','这个有点儿大。','Cái này hơi lớn.']],tip:'比 dùng để so sánh hơn; 太…了 diễn tả mức độ quá hoặc cảm thán.',warning:['Không thêm 很 sau 比: A 比 B 贵 ✓','有点儿 thường mang sắc thái chưa vừa ý.']},
 {id:'travel',level:'HSK 3',num:'07',title:'Đi lại & hỏi đường',zh:'交通与问路',desc:'Hỏi đường, chọn phương tiện và mô tả vị trí.',time:17,words:[['怎么','zěnme','như thế nào'],['地铁','dìtiě','tàu điện ngầm'],['公共汽车','gōnggòng qìchē','xe buýt'],['车站','chēzhàn','trạm xe'],['前面','qiánmiàn','phía trước'],['旁边','pángbiān','bên cạnh'],['离','lí','cách'],['到','dào','đến']],patterns:[['怎么去…？','去火车站怎么走？','Đi đến ga tàu thế nào?'],['A 离 B…','学校离我家很近。','Trường học gần nhà tôi.'],['坐 + phương tiện','我们坐地铁去。','Chúng ta đi bằng tàu điện ngầm.']],tip:'离 mô tả khoảng cách giữa hai nơi; 从…到… mô tả điểm đầu và điểm cuối.',warning:['坐车 = đi xe; 做车 ❌ vì 做 nghĩa là làm.','前面 là phía trước; 以前 là trước đây.']},
 {id:'hobbies',level:'HSK 3',num:'08',title:'Sở thích & thời tiết',zh:'爱好与天气',desc:'Nói sở thích, tần suất và kế hoạch theo thời tiết.',time:17,words:[['喜欢','xǐhuan','thích'],['运动','yùndòng','thể thao'],['游泳','yóuyǒng','bơi'],['旅行','lǚxíng','du lịch'],['天气','tiānqì','thời tiết'],['晴天','qíngtiān','trời nắng'],['下雨','xiàyǔ','mưa'],['常常','chángcháng','thường xuyên']],patterns:[['喜欢 + V/O','我喜欢听音乐。','Tôi thích nghe nhạc.'],['常常 + V','她常常去游泳。','Cô ấy thường đi bơi.'],['因为…所以…','因为下雨，所以我不去。','Vì trời mưa nên tôi không đi.']],tip:'喜欢 có thể đi với danh từ hoặc động từ; 很喜欢 nhấn mạnh rất thích.',warning:['天气很好 = thời tiết đẹp; không nói 天气很喜欢.','因为…所以… có thể dùng đủ cả hai vế.']},
 {id:'health',level:'HSK 3',num:'09',title:'Sức khỏe & kế hoạch',zh:'健康与计划',desc:'Mô tả triệu chứng, đưa lời khuyên và nói dự định.',time:18,words:[['身体','shēntǐ','cơ thể, sức khỏe'],['生病','shēngbìng','bị ốm'],['头疼','tóuténg','đau đầu'],['休息','xiūxi','nghỉ ngơi'],['药','yào','thuốc'],['应该','yīnggāi','nên'],['打算','dǎsuàn','dự định'],['希望','xīwàng','hy vọng']],patterns:[['怎么了？','你怎么了？我头疼。','Bạn sao vậy? Tôi bị đau đầu.'],['应该 + V','你应该多休息。','Bạn nên nghỉ ngơi nhiều.'],['打算 + V','我打算明天去医院。','Tôi dự định ngày mai đi bệnh viện.']],tip:'应该 đưa lời khuyên; 必须 thể hiện bắt buộc mạnh hơn.',warning:['吃药 = uống thuốc, không dùng 喝药 trong tiếng Phổ thông chuẩn.','多 + động từ: 多喝水 = uống nhiều nước hơn.']}
];

const conversations=[
 {id:'first-day',label:'Làm quen',icon:'你',title:'Gặp một người bạn mới',desc:'Chào hỏi, hỏi tên và quốc tịch.',lines:[['A','你好！你叫什么名字？','Nǐ hǎo! Nǐ jiào shénme míngzi?','Xin chào! Bạn tên là gì?'],['B','我叫小明。你呢？','Wǒ jiào Xiǎomíng. Nǐ ne?','Tôi tên Tiểu Minh. Còn bạn?'],['A','我叫安娜。我是越南人。','Wǒ jiào Ānnà. Wǒ shì Yuènán rén.','Tôi tên Anna. Tôi là người Việt Nam.'],['B','很高兴认识你！','Hěn gāoxìng rènshi nǐ!','Rất vui được gặp bạn!']]},
 {id:'restaurant',label:'Ở nhà hàng',icon:'吃',title:'Gọi món đơn giản',desc:'Hỏi món, gọi đồ ăn và hỏi giá.',lines:[['A','你好，你想吃什么？','Nǐ hǎo, nǐ xiǎng chī shénme?','Xin chào, bạn muốn ăn gì?'],['B','我要一碗牛肉面。','Wǒ yào yì wǎn niúròu miàn.','Tôi muốn một bát mì bò.'],['A','你喝什么？','Nǐ hē shénme?','Bạn uống gì?'],['B','一杯茶。多少钱？','Yì bēi chá. Duōshao qián?','Một cốc trà. Bao nhiêu tiền?']]},
 {id:'directions',label:'Hỏi đường',icon:'路',title:'Tìm ga tàu điện',desc:'Hỏi vị trí và cách di chuyển.',lines:[['A','请问，地铁站在哪儿？','Qǐngwèn, dìtiě zhàn zài nǎr?','Xin hỏi, ga tàu điện ở đâu?'],['B','在银行旁边。','Zài yínháng pángbiān.','Ở bên cạnh ngân hàng.'],['A','离这儿远吗？','Lí zhèr yuǎn ma?','Có xa đây không?'],['B','不远，走路五分钟。','Bù yuǎn, zǒulù wǔ fēnzhōng.','Không xa, đi bộ năm phút.']]},
 {id:'doctor',label:'Đi khám bệnh',icon:'医',title:'Nói về sức khỏe',desc:'Mô tả triệu chứng và nghe lời khuyên.',lines:[['A','你怎么了？','Nǐ zěnme le?','Bạn sao vậy?'],['B','我头疼，还有点儿发烧。','Wǒ tóuténg, hái yǒudiǎnr fāshāo.','Tôi đau đầu và hơi sốt.'],['A','你应该多休息，多喝水。','Nǐ yīnggāi duō xiūxi, duō hē shuǐ.','Bạn nên nghỉ ngơi và uống nhiều nước.'],['B','好的，谢谢。','Hǎo de, xièxie.','Được, cảm ơn.']]}
];

const quiz=[
 {type:'TỪ VỰNG',q:'“朋友” có nghĩa là gì?',o:['Gia đình','Bạn bè','Giáo viên'],a:1,e:'朋友 (péngyou) nghĩa là bạn bè.'},
 {type:'GIỚI THIỆU',q:'Chọn câu đúng: “Tôi là người Việt Nam.”',o:['我是越南人。','我在越南人。','我有越南人。'],a:0,e:'是 nối chủ ngữ với danh từ: 我 + 是 + 越南人.'},
 {type:'GIA ĐÌNH',q:'我家 ___ 四口人。',o:['是','有','在'],a:1,e:'有 diễn tả sở hữu hoặc sự tồn tại: gia đình tôi có bốn người.'},
 {type:'THỜI GIAN',q:'Cách nói đúng của “9 giờ sáng” là:',o:['九点上午','上午九点','九上午点'],a:1,e:'Thời gian nói từ lớn đến nhỏ: buổi sáng rồi đến 9 giờ.'},
 {type:'TRẠNG THÁI',q:'我 ___ 看书。 (Tôi đang đọc sách.)',o:['正在','已经','还没'],a:0,e:'正在 đứng trước động từ để chỉ hành động đang diễn ra.'},
 {type:'ĂN UỐNG',q:'“Tôi muốn uống trà” là:',o:['我想喝茶。','我想吃茶。','我喝想茶。'],a:0,e:'Đồ uống dùng 喝; 想 đứng trước động từ.'},
 {type:'SO SÁNH',q:'这件衣服 ___ 贵了。 (Bộ đồ này đắt quá.)',o:['比','太','很比'],a:1,e:'太 + tính từ + 了 diễn tả “quá…” hoặc cảm thán.'},
 {type:'ĐI LẠI',q:'学校 ___ 我家很近。',o:['从','到','离'],a:2,e:'A 离 B + xa/gần dùng để nói khoảng cách.'},
 {type:'SỞ THÍCH',q:'她常常去 ___。 (Cô ấy thường đi bơi.)',o:['游泳','天气','晴天'],a:0,e:'游泳 nghĩa là bơi; 去游泳 là đi bơi.'},
 {type:'NGUYÊN NHÂN',q:'因为下雨，___ 我不去。',o:['但是','所以','如果'],a:1,e:'因为…所以… = bởi vì… nên…'},
 {type:'SỨC KHỎE',q:'Bạn nên nghỉ ngơi nhiều:',o:['你正在休息。','你应该多休息。','你喜欢休息。'],a:1,e:'应该 + động từ dùng để đưa lời khuyên.'},
 {type:'KẾ HOẠCH',q:'我 ___ 明天去医院。 (Tôi dự định ngày mai đi bệnh viện.)',o:['打算','已经','觉得'],a:0,e:'打算 + động từ diễn tả dự định hoặc kế hoạch.'}
];
